## build: build application binary.
build:
	go build

## run: run main.go
run:
	go build
	./api

## unit-test: run tests on internal packages
unit-test:
	go test -v ../internal/...

## integration-test: run integration test suite using test fixtures
integration-test:
	go test -v ../test/integration-tests